name: Mend Prioritize Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prioritize:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv --user
        pip install -r requirements.txt
    
    - name: Mend Prioritize Scan
      env:
        WS_APIKEY: '5d8562edabf7471082f8fa98d79f343a6b3a4dcaa4674f528a3b809193a9225d'
        WS_USERKEY: 'cea34b2d1d5c4112a629aded65a526f923bcc437450e4373877fb43b450e11d0'
        WS_WSS_URL: https://saas-eu.mend.io/agent
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}
        ##WS_PROJECTNAME: ${{github.ref}}_Prioritize
        #WS_ENABLEIMPACTANALYSIS: true
        #WS_RESOLVEALLDEPENDENCIES: false
        #WS_PYTHON_RESOLVEDEPENDENCIES: true
        #WS_FILESYSTEMSCAN: false
        #WS_GENERATEPROJECTDETAILSJSON: true
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
        echo "Integrity Check Failed"
        else
            echo "Integrity Check Passed"
            echo "Starting Mend Scan"
        fi
        java -jar wss-unified-agent.jar -d ./ projectPerFolder true
